bot:
  token: YOUR_BOT_TOKEN # telegram bot token
  admin: # telegram id of the admins
    - YOUR_ADMIN_ID
    - YOUR_ADMIN_ID
    - YOUR_ADMIN_ID
  socks5: # socks5 proxy settings
    enable: false
    host: localhost
    port: 1080
    user:
    password:
ctrl:
  # support markdown style: https://core.telegram.org/bots/api#markdown-style
  notice: |
    *YOUR_NOTICE_MESSAGE*
    _YOUR_NOTICE_MESSAGE_
    `YOUR_NOTICE_MESSAGE`
    [YOUR_NOTICE_MESSAGE](https://www.google.com)
  i18n: ./config/i18n # i18n files directory
  default_language: zh-cn # default language
  search:
    page_size: 10 # number of results per page
storage:
  cache:
    driver: gocache # driver: gocache
  kv:
    driver: bolt # driver: bolt
    options:
      path: ./data/data.kv # bolt db path
  search:
    driver: bleve # driver: bleve
    options:
      path: ./data/msg.index # bleve index path
      dict: ./config/dict.txt # dictionary file path
